apiVersion: v1
kind: Pod
metadata:
  name: nats
  namespace: go-micro
  labels:
    app: nats
spec:
  restartPolicy: "Always"
  containers:
    - name: nats
      image: nats:2.10.22
      ports:
        - containerPort: 4222
        - containerPort: 8222
        - containerPort: 6222
      args:
        - "-js" # Enables JetStream for persistent storage (optional)
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: go-micro
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222
    - name: monitoring
      port: 8222
      targetPort: 8222
