apiVersion: v1
kind: Service
metadata:
  name: rest-api-svc
  namespace: go-micro
  labels:
    app: rest-api-svc
spec:
  ports:
    - name: rest-api-svc
      port: 3004
      targetPort: 5678
  selector:
    app: rest-api-svc
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rest-api-svc
subsets:
  - addresses:
      - ip: 10.62.176.1
    ports:
      - port: 3004