apiVersion: v1
kind: Service
metadata:
  name: rest-api-svc
  namespace: go-micro
  labels:
    app: rest-api-svc
spec:
  type: LoadBalancer
  ports:
    - name: rest-api-svc
      port: 80
      targetPort: 5678
  selector:
    app: rest-api-svc
