apiVersion: v1
kind: Service
metadata:
  name: account-svc
  namespace: go-micro
  labels:
    app: account-svc
spec:
  ports:
    - port: 5678
      name: account-svc
      targetPort: 5678
  selector:
    app: account-svc
